<?php

/**
 * @file
 * Code for image_extra_field module.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_form_FORM_ID_alter() for field_config_edit_form().
 *
 * {@inheritdoc}
 */
function image_extra_field_form_field_config_edit_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $field = $form_state->getFormObject()->getEntity();

  if ($field->getType() == 'image') {
    $form['extra_field_enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Enable %field field', ['%field' => 'extra']),
      '#description' => t('The extra field may be used to store extra information like a caption or byline.'),
      '#weight' => 50,
      '#default_value' => $field->getThirdPartySetting('image_extra_field', 'extra_field_enabled'),
    ];

    $form['#entity_builders'][] = 'image_extra_field_image_field_form_builder';
  }
}

/**
 * Entity builder for image fields.
 *
 * @param string $entity_type
 * @param \Drupal\field\Entity\FieldConfig $field
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @see image_extra_field_form_field_config_edit_form_alter()
 */
function image_extra_field_image_field_form_builder($entity_type, FieldConfig $field, array &$form, FormStateInterface $form_state) {
  if ($form_state->getValue('extra_field_enabled')) {
    $field->setThirdPartySetting('image_extra_field', 'extra_field_enabled', $form_state->getValue('extra_field_enabled'));
    return;
  }

  $field->unsetThirdPartySetting('image_extra_field', 'extra_field_enabled');
}

function image_extra_field_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $widget = $context['widget'];

  if ($widget->getPluginId() == 'image_image') {
    $entity = $form_state->getFormObject()->getEntity();
    $field = $entity->getFieldDefinition($element['#field_name']);
    $extra_field_enabled = isset($field->getThirdPartySettings('image_extra_field')['extra_field_enabled']) ? TRUE : FALSE;
    $default_value = $element['#default_value'];

    $element['image_extra_field'] = array(
      '#title' => t('Extra field'),
      '#type' => 'textfield',
      '#default_value' => '', //$entity->getThirdPartySetting('image_extra_field', 'image_extra_field'),
      '#description' => t('Enter extra information like a caption or byline. '),
      '#maxlength' => 512,
      '#access' => (bool) $default_value['fids'] && $extra_field_enabled,
    );

    $element['#entity_builders'][] = 'image_extra_field_image_widget_form_builder';
  }
}

function image_extra_field_image_widget_form_builder($entity_type, \Drupal\Core\Entity $field, array &$form, FormStateInterface $form_state) {
//  print('test');
//  if ($form_state->getValue('image_extra_field')) {
//    $field->setThirdPartySetting('image_extra_field', 'image_extra_field', $form_state->getValue('image_extra_field'));
//    return;
//  }
//
//  $field->unsetThirdPartySetting('image_extra_field', 'image_extra_field');
}

function image_extra_field_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface && $entity->isTranslatable()) {
    $route_match = \Drupal::routeMatch();
    \Drupal::service('content_translation.synchronizer')->synchronizeFields($entity, $entity->language()->getId(), $route_match->getParameter('source_langcode'));
  }
}

function image_extra_field_form_alter($form, $form_state, $form_id) {
//  print($form_id);
//  print($form_state->getBuildInfo()['base_form_id']);
}
